---
theme: "hugo-blanco"

baseurl: "http://xn--cristbal-z3a.com/"
canonifyurls: true

languageCode: "en-us"
contentdir: "content"
publishdir: "public"

builddrafts: false

title: "Cristóbal Carnero Liñán"
author: "Cristóbal Carnero Liñán"

indexes:
    category: "categories"
    tag: "tags"

params:
    tagline: "Server-side DevOps."
    description: "Cristóbal personal web."
    keywords: "cristobal,carnero,linan,cv,curriculum,resume,web,personal,home,website,blog"

    titleeffect: "3d" # 3d, 3d-float, shadow-multiple, outline, stonewash

    github: "https://github.com/cristobalcl"
    linkedin: "http://es.linkedin.com/in/ccarnerolinan/"
    googleplus: "https://www.google.com/+Crist%C3%B3balCarneroLi%C3%B1%C3%A1n"
    email: "ccarnerolinan@gmail.com"

    disqusShortname: "cristbal"
...
