---
theme: "hugo-blanco"

baseurl: "https://cristobal.dev/"
canonifyurls: true

languageCode: "en-us"
contentdir: "content"
publishdir: "public"

builddrafts: false

title: "Cristóbal Carnero Liñán"
author: "Cristóbal Carnero Liñán"

indexes:
    category: "categories"
    tag: "tags"

params:
    tagline: "Backend Developer and DevOps."
    description: "Cristóbal personal web."
    keywords: "cristobal,carnero,linan,backend,engineer,data,devops,python,cv,curriculum,resume,web,personal,home,website,blog"
    titleeffect: "3d" # 3d, 3d-float, shadow-multiple, outline, stonewash

    github: "https://github.com/cristobalcl"
    linkedin: "http://es.linkedin.com/in/ccarnerolinan/"
    twitter: "https://twitter.com/cristobal_dev"
    medium: "https://medium.com/@cristobalcl"
    email: "ccarnerolinan@gmail.com"

    googleAnalyticsTrackingID: "UA-66537544-1"
    disqusShortname: "cristbal"
...
