name: Publish web

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Hugo
      run: sudo snap install hugo --channel=extended

    - name: Setup
      run: |
        cd $GITHUB_WORKSPACE
        git submodule sync
        git submodule update --init

    - name: Build
      run: |
        hugo

#    - name: Publish
#      run: |
#        cd public
#        git config user.email "ccarnerolinan@gmail.com"
#        git config user.name "Cristóbal Carnero Liñán"
#        git remote add gh-page git@github.com:cristobalcl/cristobalcl.github.io.git
#        git add .
#        git commit -m "Publish"
#        git branch tmp-branch
#        git checkout master
#        git merge tmp-branch
#        git remote get-url --push origin
#        git push gh-page master
    - name: Publish
      uses: johno/actions-push-subdirectories@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: public cristobalcl cristobalcl.github.io
