name: Publish web

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Hugo
      run: sudo snap install hugo --channel=extended

    - name: Build
      run: |
        cd $GITHUB_WORKSPACE
        hugo
